import { collection, getDocs, doc, setDoc } from 'firebase/firestore'
import { db } from './firebase'
import type { SiteImage } from './admin-data'

export const SEED_DATA: SiteImage[] = [
  // ─── HOME PAGE (14 images) ───
  {
    id: 'home-hero-bg',
    page: 'home',
    section: 'Hero Background',
    name: 'Main Hero Background',
    location: 'Home → Hero Section',
    stockUrl: 'https://images.unsplash.com/photo-1636466497217-26a8cbeaf0aa?auto=format&fit=crop&w=1920&q=80',
    customUrl: '',
    customPath: '',
    recommendedSize: '1920×1080',
    order: 1,
  },
  {
    id: 'home-product-business-cards',
    page: 'home',
    section: 'Product Cards',
    name: 'Business Cards',
    location: 'Home → Hero → Product Cards',
    stockUrl: 'https://images.unsplash.com/photo-1611532736597-de2d4265fba3?auto=format&fit=crop&w=500&q=80',
    customUrl: '',
    customPath: '',
    recommendedSize: '500×300',
    order: 2,
  },
  {
    id: 'home-product-brochures',
    page: 'home',
    section: 'Product Cards',
    name: 'Tri-Fold Brochures',
    location: 'Home → Hero → Product Cards',
    stockUrl: 'https://images.unsplash.com/photo-1586075010923-2dd4570fb338?auto=format&fit=crop&w=500&q=80',
    customUrl: '',
    customPath: '',
    recommendedSize: '500×300',
    order: 3,
  },
  {
    id: 'home-product-packaging',
    page: 'home',
    section: 'Product Cards',
    name: 'Custom Packaging',
    location: 'Home → Hero → Product Cards',
    stockUrl: 'https://images.unsplash.com/photo-1605000797499-95a51c5269ae?auto=format&fit=crop&w=500&q=80',
    customUrl: '',
    customPath: '',
    recommendedSize: '500×300',
    order: 4,
  },
  {
    id: 'home-product-banners',
    page: 'home',
    section: 'Product Cards',
    name: 'Banners & Signs',
    location: 'Home → Hero → Product Cards',
    stockUrl: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?auto=format&fit=crop&w=500&q=80',
    customUrl: '',
    customPath: '',
    recommendedSize: '500×300',
    order: 5,
  },
  {
    id: 'home-industry-healthcare',
    page: 'home',
    section: 'Industry Cards',
    name: 'Healthcare',
    location: 'Home → Industries We Serve',
    stockUrl: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&w=600&q=80',
    customUrl: '',
    customPath: '',
    recommendedSize: '600×420',
    order: 6,
  },
  {
    id: 'home-industry-hospitality',
    page: 'home',
    section: 'Industry Cards',
    name: 'Hospitality',
    location: 'Home → Industries We Serve',
    stockUrl: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=600&q=80',
    customUrl: '',
    customPath: '',
    recommendedSize: '600×420',
    order: 7,
  },
  {
    id: 'home-industry-education',
    page: 'home',
    section: 'Industry Cards',
    name: 'Education',
    location: 'Home → Industries We Serve',
    stockUrl: 'https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=600&q=80',
    customUrl: '',
    customPath: '',
    recommendedSize: '600×420',
    order: 8,
  },
  {
    id: 'home-industry-automotive',
    page: 'home',
    section: 'Industry Cards',
    name: 'Automotive',
    location: 'Home → Industries We Serve',
    stockUrl: 'https://images.unsplash.com/photo-1549924231-f129b911e442?auto=format&fit=crop&w=600&q=80',
    customUrl: '',
    customPath: '',
    recommendedSize: '600×420',
    order: 9,
  },
  {
    id: 'home-features-bg',
    page: 'home',
    section: 'Features Background',
    name: 'Features Section Background',
    location: 'Home → Features Section',
    stockUrl: 'https://images.unsplash.com/photo-1562654501-a0ccc0fc3fb1?auto=format&fit=crop&w=1920&q=80',
    customUrl: '',
    customPath: '',
    recommendedSize: '1920×1080',
    order: 10,
  },
  {
    id: 'home-facility-1',
    page: 'home',
    section: 'Facility Strip',
    name: 'Digital Press Room',
    location: 'Home → Features → Facility Strip',
    stockUrl: 'https://images.unsplash.com/photo-1636466497217-26a8cbeaf0aa?auto=format&fit=crop&w=200&q=80',
    customUrl: '',
    customPath: '',
    recommendedSize: '200×130',
    order: 11,
  },
  {
    id: 'home-facility-2',
    page: 'home',
    section: 'Facility Strip',
    name: 'Offset Printing',
    location: 'Home → Features → Facility Strip',
    stockUrl: 'https://images.unsplash.com/photo-1581092160562-40aa08e78837?auto=format&fit=crop&w=200&q=80',
    customUrl: '',
    customPath: '',
    recommendedSize: '200×130',
    order: 12,
  },
  {
    id: 'home-facility-3',
    page: 'home',
    section: 'Facility Strip',
    name: 'Design Studio',
    location: 'Home → Features → Facility Strip',
    stockUrl: 'https://images.unsplash.com/photo-1542621334-a254cf47733d?auto=format&fit=crop&w=200&q=80',
    customUrl: '',
    customPath: '',
    recommendedSize: '200×130',
    order: 13,
  },
  {
    id: 'home-cta-bg',
    page: 'home',
    section: 'CTA Background',
    name: 'CTA Section Background',
    location: 'Home → CTA Section',
    stockUrl: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1920&q=80',
    customUrl: '',
    customPath: '',
    recommendedSize: '1920×1080',
    order: 14,
  },

  // ─── SERVICES PAGE (7 images) ───
  {
    id: 'services-hero-bg',
    page: 'services',
    section: 'Hero Background',
    name: 'Services Hero',
    location: 'Services → Hero Section',
    stockUrl: 'https://images.unsplash.com/photo-1636466497217-26a8cbeaf0aa?auto=format&fit=crop&w=1920&q=80',
    customUrl: '',
    customPath: '',
    recommendedSize: '1920×1080',
    order: 1,
  },
  {
    id: 'services-commercial',
    page: 'services',
    section: 'Service Categories',
    name: 'Commercial Printing',
    location: 'Services → Commercial Printing',
    stockUrl: 'https://images.unsplash.com/photo-1611532736597-de2d4265fba3?auto=format&fit=crop&w=800&q=80',
    customUrl: '',
    customPath: '',
    recommendedSize: '800×400',
    order: 2,
  },
  {
    id: 'services-packaging',
    page: 'services',
    section: 'Service Categories',
    name: 'Custom Packaging',
    location: 'Services → Custom Packaging',
    stockUrl: 'https://images.unsplash.com/photo-1605000797499-95a51c5269ae?auto=format&fit=crop&w=800&q=80',
    customUrl: '',
    customPath: '',
    recommendedSize: '800×400',
    order: 3,
  },
  {
    id: 'services-large-format',
    page: 'services',
    section: 'Service Categories',
    name: 'Large Format',
    location: 'Services → Large Format',
    stockUrl: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?auto=format&fit=crop&w=800&q=80',
    customUrl: '',
    customPath: '',
    recommendedSize: '800×400',
    order: 4,
  },
  {
    id: 'services-office',
    page: 'services',
    section: 'Service Categories',
    name: 'Office & Forms',
    location: 'Services → Office & Forms',
    stockUrl: 'https://images.unsplash.com/photo-1586075010923-2dd4570fb338?auto=format&fit=crop&w=800&q=80',
    customUrl: '',
    customPath: '',
    recommendedSize: '800×400',
    order: 5,
  },
  {
    id: 'services-capabilities-bg',
    page: 'services',
    section: 'Capabilities Background',
    name: 'Capabilities Section',
    location: 'Services → Capabilities Section',
    stockUrl: 'https://images.unsplash.com/photo-1581092160562-40aa08e78837?auto=format&fit=crop&w=1920&q=80',
    customUrl: '',
    customPath: '',
    recommendedSize: '1920×1080',
    order: 6,
  },
  {
    id: 'services-cta-bg',
    page: 'services',
    section: 'CTA Background',
    name: 'Services CTA',
    location: 'Services → CTA Section',
    stockUrl: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1920&q=80',
    customUrl: '',
    customPath: '',
    recommendedSize: '1920×1080',
    order: 7,
  },

  // ─── ABOUT PAGE (10 images) ───
  {
    id: 'about-hero-bg',
    page: 'about',
    section: 'Hero Background',
    name: 'About Hero',
    location: 'About → Hero Section',
    stockUrl: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1920&q=80',
    customUrl: '',
    customPath: '',
    recommendedSize: '1920×1080',
    order: 1,
  },
  {
    id: 'about-team-kassa',
    page: 'about',
    section: 'Team Photos',
    name: 'Kassa — Founder',
    location: 'About → Team → Kassa',
    stockUrl: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=400&q=80',
    customUrl: '',
    customPath: '',
    recommendedSize: '400×500',
    order: 2,
  },
  {
    id: 'about-team-marcel',
    page: 'about',
    section: 'Team Photos',
    name: 'Marcel — Marketing',
    location: 'About → Team → Marcel',
    stockUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=400&q=80',
    customUrl: '',
    customPath: '',
    recommendedSize: '400×500',
    order: 3,
  },
  {
    id: 'about-team-estevan',
    page: 'about',
    section: 'Team Photos',
    name: 'Estevan — Designer',
    location: 'About → Team → Estevan',
    stockUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=400&q=80',
    customUrl: '',
    customPath: '',
    recommendedSize: '400×500',
    order: 4,
  },
  {
    id: 'about-team-joao',
    page: 'about',
    section: 'Team Photos',
    name: 'João — Consultant',
    location: 'About → Team → João Serro',
    stockUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
    customUrl: '',
    customPath: '',
    recommendedSize: '400×500',
    order: 5,
  },
  {
    id: 'about-facility-digital',
    page: 'about',
    section: 'Facility Tour',
    name: 'Digital Press Room',
    location: 'About → Facility Tour → Digital Press',
    stockUrl: 'https://images.unsplash.com/photo-1636466497217-26a8cbeaf0aa?auto=format&fit=crop&w=600&q=80',
    customUrl: '',
    customPath: '',
    recommendedSize: '600×400',
    order: 6,
  },
  {
    id: 'about-facility-offset',
    page: 'about',
    section: 'Facility Tour',
    name: 'Offset Printing',
    location: 'About → Facility Tour → Offset Printing',
    stockUrl: 'https://images.unsplash.com/photo-1581092160562-40aa08e78837?auto=format&fit=crop&w=600&q=80',
    customUrl: '',
    customPath: '',
    recommendedSize: '600×400',
    order: 7,
  },
  {
    id: 'about-facility-design',
    page: 'about',
    section: 'Facility Tour',
    name: 'Design Studio',
    location: 'About → Facility Tour → Design Studio',
    stockUrl: 'https://images.unsplash.com/photo-1542621334-a254cf47733d?auto=format&fit=crop&w=600&q=80',
    customUrl: '',
    customPath: '',
    recommendedSize: '600×400',
    order: 8,
  },
  {
    id: 'about-facility-finishing',
    page: 'about',
    section: 'Facility Tour',
    name: 'Finishing Area',
    location: 'About → Facility Tour → Finishing Area',
    stockUrl: 'https://images.unsplash.com/photo-1565793298595-6a879b1d9492?auto=format&fit=crop&w=600&q=80',
    customUrl: '',
    customPath: '',
    recommendedSize: '600×400',
    order: 9,
  },
  {
    id: 'about-cta-bg',
    page: 'about',
    section: 'CTA Background',
    name: 'About CTA',
    location: 'About → CTA Section',
    stockUrl: 'https://images.unsplash.com/photo-1521737711867-e3b97375f902?auto=format&fit=crop&w=1920&q=80',
    customUrl: '',
    customPath: '',
    recommendedSize: '1920×1080',
    order: 10,
  },

  // ─── PORTFOLIO PAGE (2 images) ───
  {
    id: 'portfolio-hero-bg',
    page: 'portfolio',
    section: 'Hero Background',
    name: 'Portfolio Hero',
    location: 'Portfolio → Hero Section',
    stockUrl: 'https://images.unsplash.com/photo-1542621334-a254cf47733d?auto=format&fit=crop&w=1920&q=80',
    customUrl: '',
    customPath: '',
    recommendedSize: '1920×1080',
    order: 1,
  },
  {
    id: 'portfolio-cta-bg',
    page: 'portfolio',
    section: 'CTA Background',
    name: 'Portfolio CTA',
    location: 'Portfolio → CTA Section',
    stockUrl: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1920&q=80',
    customUrl: '',
    customPath: '',
    recommendedSize: '1920×1080',
    order: 2,
  },

  // ─── CONTACT PAGE (2 images) ───
  {
    id: 'contact-hero-bg',
    page: 'contact',
    section: 'Hero Background',
    name: 'Contact Hero',
    location: 'Contact → Hero Section',
    stockUrl: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1920&q=80',
    customUrl: '',
    customPath: '',
    recommendedSize: '1920×1080',
    order: 1,
  },
  {
    id: 'contact-cta-bg',
    page: 'contact',
    section: 'CTA Background',
    name: 'Contact CTA',
    location: 'Contact → CTA Section',
    stockUrl: 'https://images.unsplash.com/photo-1521737711867-e3b97375f902?auto=format&fit=crop&w=1920&q=80',
    customUrl: '',
    customPath: '',
    recommendedSize: '1920×1080',
    order: 2,
  },
]

export async function seedSiteImages() {
  const snapshot = await getDocs(collection(db, 'siteImages'))
  if (!snapshot.empty) return

  const promises = SEED_DATA.map((item) => {
    const { id, ...data } = item
    return setDoc(doc(db, 'siteImages', id), data)
  })
  await Promise.all(promises)
}
